export const products = [
  {
    pName: "Smartphone",
    description: "Latest model smartphone",
    price: 699,
    category: "electronics",
    stock: true,
  },
  {
    pName: "Laptop",
    description: "High performance laptop",
    price: 999,
    category: "electronics",
    stock: true,
  },
  {
    pName: "Headphones",
    description: "Noise-cancelling headphones",
    price: 199,
    category: "electronics",
    stock: true,
  },
  {
    pName: "Smartwatch",
    description: "Wearable smart device",
    price: 299,
    category: "electronics",
    stock: true,
  },
  {
    pName: "E-Reader",
    description: "Portable e-reader with high resolution display",
    price: 129,
    category: "electronics",
    stock: true,
  },
  {
    pName: "Fantasy Novel",
    description: "A popular fantasy novel",
    price: 15,
    category: "books",
    stock: true,
  },
  {
    pName: "Science Fiction Novel",
    description: "A thrilling science fiction novel",
    price: 20,
    category: "books",
    stock: true,
  },
  {
    pName: "Cookbook",
    description: "A collection of recipes from around the world",
    price: 25,
    category: "books",
    stock: true,
  },
  {
    pName: "Biography",
    description: "An inspiring biography of a famous person",
    price: 30,
    category: "books",
    stock: true,
  },
  {
    pName: "Self-help Book",
    description: "A guide to personal development and success",
    price: 18,
    category: "books",
    stock: true,
  },
  {
    pName: "T-shirt",
    description: "Comfortable cotton t-shirt",
    price: 12,
    category: "clothing",
    stock: true,
  },
  {
    pName: "Jeans",
    description: "Stylish and durable jeans",
    price: 40,
    category: "clothing",
    stock: true,
  },
  {
    pName: "Jacket",
    description: "Warm and cozy jacket for winter",
    price: 60,
    category: "clothing",
    stock: true,
  },
  {
    pName: "Sneakers",
    description: "Comfortable and stylish sneakers",
    price: 50,
    category: "clothing",
    stock: true,
  },
  {
    pName: "Dress",
    description: "Elegant evening dress",
    price: 80,
    category: "clothing",
    stock: true,
  },
  {
    pName: "Blender",
    description: "High-speed blender for smoothies and more",
    price: 70,
    category: "home-kitchen",
    stock: true,
  },
  {
    pName: "Coffee Maker",
    description: "Automatic coffee maker with timer",
    price: 100,
    category: "home-kitchen",
    stock: true,
  },
  {
    pName: "Vacuum Cleaner",
    description: "Powerful vacuum cleaner for all surfaces",
    price: 150,
    category: "home-kitchen",
    stock: true,
  },
  {
    pName: "Air Fryer",
    description: "Healthy cooking with an air fryer",
    price: 90,
    category: "home-kitchen",
    stock: true,
  },
  {
    pName: "Yoga Mat",
    description: "Non-slip yoga mat",
    price: 25,
    category: "sports-outdoors",
    stock: true,
  },
  {
    pName: "Running Shoes",
    description: "Lightweight and comfortable running shoes",
    price: 60,
    category: "sports-outdoors",
    stock: true,
  },
  {
    pName: "Dumbbells",
    description: "Set of adjustable dumbbells",
    price: 80,
    category: "sports-outdoors",
    stock: true,
  },
  {
    pName: "Tent",
    description: "Spacious and durable camping tent",
    price: 120,
    category: "sports-outdoors",
    stock: true,
  },
  {
    pName: "Skincare Set",
    description: "Complete skincare set for glowing skin",
    price: 50,
    category: "beauty-personal-care",
    stock: true,
  },
  {
    pName: "Hair Dryer",
    description: "High-power hair dryer",
    price: 40,
    category: "beauty-personal-care",
    stock: true,
  },
];

export const categories = [
  { title: "Electronics", slug: "electronics" },
  { title: "Books", slug: "books" },
  { title: "Clothing", slug: "clothing" },
  { title: "Home & Kitchen", slug: "home-kitchen" },
  { title: "Sports & Outdoors", slug: "sports-outdoors" },
  { title: "Beauty & Personal Care", slug: "beauty-personal-care" },
];
